Haveak-Pro/Models/Mesajlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haveak_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int ID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Gonderen_Ref { get; set; }
        public Nullable<int> Alici_Ref { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Icerik { get; set; }
        public System.TimeSpan Saat { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}

Haveak-Pro/Areas/PANEL/Controllers/MesajlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Haveak_Pro.Models;

namespace Haveak_Pro.Areas.PANEL.Controllers
{
    public class MesajlarController : Controller
    {
        //
        // GET: /Panel/Mesajlar/
        Heas_UzakEntities Entity = new Heas_UzakEntities();
        public ActionResult Index()
        {
            var list = Entity.Mesajlars.ToList();
            ViewBag.Personel = Entity.Personels.Where(r => r.IsActive == true && r.IsDelete == false).ToList();
            return View(list);
        }

        [HttpPost]
        public ActionResult SendMessage(int Personel_Ref, string Icerik)
        {
            var mesaj = new Mesajlar();
            mesaj.IsActive = true;
            mesaj.IsDelete = false;
            //mesaj.Personel_Ref = Personel_Ref;
            mesaj.Icerik = Icerik;           
            mesaj.Tarih = DateTime.Now;
            Entity.Mesajlars.Add(mesaj);
            Entity.SaveChanges();
            return RedirectToAction("Index", "Mesajlar", new { area="Panel" });
        }

        

    }
}

Haveak-Pro/Controllers/MesajIslemlerController.cs
using Haveak_Pro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Haveak_Pro.Controllers
{

    public class MesajIslemlerController : Controller
    {
        //
        // GET: /Panel/MesajIslemler/
        //public MesajIslemlerController()
        //{
        //    AktifKullanici.Aktif.SecilenModul = "PANEL";
        //}

        Heas_UzakEntities Entity = new Heas_UzakEntities();
       
       
        public ActionResult Mesajlar()
        {
            var kimlik = AktifKullanici.Aktif.User_Ref;
            DateTime bugun = DateTime.Now.Date;

            if (!UserRoleName.ADMIN_Egitim.InRole() && !UserRoleName.PANEL_AdminGiris.InRole())
            {
                ViewBag.MesajKisiler = Entity.Kull_Rolleri.Where(t => (t.Kull_Rol_Adi.Name == UserRoleName.PANEL_AdminGiris || t.Kull_Rol_Adi.Name == UserRoleName.ADMIN_Egitim)  && t.Kullanici.Personel_Ref != kimlik && t.Kullanici.Personel.IsActive == true).Select(e => e.Kullanici).ToList();
            }
            else
            {
                ViewBag.MesajKisiler = Entity.Mesajlars.Where(t => t.IsActive == true && t.IsDelete == false && t.Alici_Ref == kimlik && t.Personel.IsActive == true).Select(w => w.Personel.Kullanicis.FirstOrDefault()).Distinct().ToList();
            }
            return View();
        }

        public ActionResult _MesajIcerikGnl(int aliciRef)
        {
            int gonderen = AktifKullanici.Aktif.User_Ref;          
            var data = Entity.Mesajlars.OrderByDescending(y => y.ID).Where(t => t.IsActive == true && t.IsDelete == false && (t.Gonderen_Ref == gonderen || t.Alici_Ref == gonderen)).ToList();
            ViewBag.AliciRef = aliciRef;
            return PartialView("_MesajDetayGenel", data);
        }

        public ActionResult PostaGelen()
        { 
            return View(); 
        }
        public ActionResult PostaGonder()
        {
            return View();
        }
       

        public ActionResult UpdateMesaj(int id, bool IsActive, bool IsDelete)
        {
            string result = "";
            try
            {
                var data = Entity.Mesajlars.Where(r => r.ID == id).FirstOrDefault();               
                data.IsActive = IsActive;
                data.IsDelete = IsDelete;
                Entity.SaveChanges();
                result = "[{\"durum\":true}]";
            }
            catch (Exception)
            {
                result = "[{\"durum\":false}]";
            }
            ContentResult cr = new ContentResult();
            cr.ContentEncoding = System.Text.Encoding.UTF8;
            cr.ContentType = "application/json";
            cr.Content = result;
            return cr;
        }
    }
}

Haveak-Pro/Views/MesajIslemler/Mesajlar.cshtml
@{
    ViewBag.Title = "Mesajlar";
    Layout = "~/Views/Shared/_LMenu.cshtml";

    var mesajKisiler = (List<Kullanici>)ViewBag.MesajKisiler;    
}
@using Haveak_Pro.Models;


<ul class="breadcrumb push-down-0">
    <li><a href="@Url.Action("Index", "Home", new { area = "" })">AnaSayfa</a></li>
    <li class="active"><a href="#">Mesajlar</a></li>
</ul>
<div class="content-frame">

    <div class="content-frame-top">
        <div class="page-title">
            <h2><span class="fa fa-comments"></span>Mesajlar</h2>
        </div>
    </div>
    <div class="content-frame-right">
        <div class="list-group list-group-contacts border-bottom push-down-10">

            <table id="Kullanicilar" class="table datatable">
                <thead>
                    <tr>
                        <th>Kişiler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in mesajKisiler)
                    {
                        <tr>
                            <td>
                                <a href="javascript:MesajDataGenelGetir('@item.Personel.ID')" class="list-group-item">
                                    <div class="list-group-status status-online"></div>
                                    <img src="~/DocumentFiles/Personel/@(item.Personel.Resim ?? "RYok.jpg")" class="pull-left" alt="@item.Personel.Adi @item.Personel.Soyadi">
                                    <span class="contacts-title">@item.Personel.Adi @item.Personel.Soyadi</span>
                                    @if (!UserRoleName.PANEL_AdminGiris.InRole() || !UserRoleName.ADMIN_Egitim.InRole())
                                    {
                                        <p>Yönetici</p>
                                    }
                                    else
                                    {
                                        <p>Kullanıcı</p>     
                                    }
                                </a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>           

        </div>      
        
           <div class="panel panel-danger">
                                <div class="panel-heading ui-draggable-handle">
                                    <h3 class="panel-title">YENİ BİLDİRİM GÖNDERİMİ</h3>
                                </div>
                                <div class="panel-body">
                                   <textarea id="Mesaj" rows="2" cols="5" class="form-control" placeholder="Mesajınız..."></textarea>
                                </div>
                                <div class="panel-footer">                                
                                    <button class="btn btn-default" onclick="MesajGonder();">Gönder</button>
                                </div>
                            </div>
          
    </div>
    <div class="content-frame-body content-frame-body-left">
        <div class="messages messages-img" id="MesajIcerik">
        </div>
    </div>
</div>

<script>   
    function MesajDataGenelGetir(gid) {       
        $.get('@Url.Action("_MesajIcerikGnl", "MesajIslemler", new { area = "" })', { aliciRef: gid }, function (data) { 
            $('#MesajIcerik').html(data);
            $('#Kullanicilar').dataTable();            
        });
    }

    function MesajGonder()
    {        
        var aliciRef = $('#AliciRef').val();
        if (aliciRef =="") {
            alert("Litfen Alıcı Seçiniz!");
            return;
        }
        var mesaj = $('#Mesaj').val();
        $.ajax({
            url: "@Url.Action("MesajGonder", "Home", new { area =""})",
            data: { 'aliciRef': aliciRef, 'mesaj': mesaj },
            success: (function (kaydet) {
                if (kaydet) {
                    MesajDataGetir();
                    $('#Mesaj').val('');
                    $('#Kullanicilar').dataTable();  
                    MesajDataGetir(aliciRef);
                }
            }),
            error: function (hata) {
                $('#hata').click();
            }
        });
    }

</script>

Haveak-Pro/Views/MesajIslemler/_MesajDetayGenel.cshtml
@model List<Mesajlar>
@{
    int aliciRef = (int)ViewBag.AliciRef;
    int kullanici = AktifKullanici.Aktif.User_Ref; 
}
@using Haveak_Pro.Models;

<input type="hidden" id="AliciRef" value="@aliciRef" />

    <div class="panel panel-default">

        <div class="panel-body scroll" style="height: 100%;">

            @foreach (var item in Model.Where(t => t.Alici_Ref == aliciRef || t.Gonderen_Ref == aliciRef))
            {
                string saat = (item.Saat.Hours < 10 ? "0" + item.Saat.Hours : item.Saat.Hours.ToString());
                string dakika = (item.Saat.Minutes < 10 ? "0" + item.Saat.Minutes : item.Saat.Minutes.ToString());
                string zaman = saat + ":" + dakika;

                string gelenGiden = item.Gonderen_Ref == kullanici ? "in" : "";
                string gonderenKisi = item.Gonderen_Ref == kullanici ? "Ben" : item.Personel.Adi + " " + item.Personel.Soyadi; 
           
                <div class="item @gelenGiden item-visible">
                    <div class="image">
                        <img src="~/DocumentFiles/Personel/@(item.Personel.Resim ?? "RYok.jpg")" alt="@gonderenKisi">
                    </div>
                    <div class="text">
                        <div class="heading">
                            <a href="#">@gonderenKisi</a>
                            <span class="date">@zaman</span>
                        </div>
                        @item.Icerik
                    </div>
                </div>
            }
        </div>
    </div>